<a href="https://colab.research.google.com/github/Boomcodes50/predictive-analytics/blob/main/Network_Security_UNSW_NB15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
import sklearn
import matplotlib.pyplot as plt
import math

In [ ]:
# Load data
merged_df = pd.read_csv('merged_cleaned.csv')


<ipython-input-104-876e6c085b57>:2: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv('merged_cleaned.csv')


Preprocessing

In [ ]:
print(merged_df.head)

<bound method NDFrame.head of         Unnamed: 0       srcip  sport          dstip dsport proto state  \
0                0  59.166.0.0   1390  149.171.126.6     53   udp   CON   
1                1  59.166.0.0  33661  149.171.126.9   1024   udp   CON   
2                2  59.166.0.6   1464  149.171.126.7     53   udp   CON   
3                3  59.166.0.5   3593  149.171.126.5     53   udp   CON   
4                4  59.166.0.3  49664  149.171.126.0     53   udp   CON   
...            ...         ...    ...            ...    ...   ...   ...   
139525      139525  59.166.0.0  52708  149.171.126.2  50651   tcp   FIN   
139526      139526  59.166.0.8  40084  149.171.126.4     22   tcp   FIN   
139527      139527  59.166.0.9   7663  149.171.126.8     22   tcp   FIN   
139528      139528  59.166.0.3  33662  149.171.126.0  31721   tcp   FIN   
139529      139529  59.166.0.4  62577  149.171.126.8     80   tcp   FIN   

             dur   sbytes   dbytes  ...  ct_ftp_cmd  ct_srv_src  ct_s

In [ ]:
merged_df.shape

(139530, 50)

In [ ]:
# Check for NaN values in each column
columns_with_nans = merged_df.columns[merged_df.isnull().any()]

# Print the columns with NaN values
print("Columns with NaN values:", columns_with_nans)


Columns with NaN values: Index(['ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat',
       'Label'],
      dtype='object')


In [ ]:
# Count the number of NaN values in each column
nan_counts = merged_df.isnull().sum()

# Print the counts of NaN values in each column
print("Counts of NaN values in each column:")
print(nan_counts)


Counts of NaN values in each column:
Unnamed: 0          0
srcip               0
sport               0
dstip               0
dsport              0
proto               0
state               0
dur                 0
sbytes              0
dbytes              0
sttl                0
dttl                0
sloss               0
dloss               0
service             0
Sload               0
Dload               0
Spkts               0
Dpkts               0
swin                0
dwin                0
stcpb               0
dtcpb               0
smeansz             0
dmeansz             0
trans_depth         0
res_bdy_len         0
Sjit                0
Djit                0
Stime               0
Ltime               0
Sintpkt             0
Dintpkt             0
tcprtt              0
synack              0
ackdat              0
is_sm_ips_ports     0
ct_state_ttl        0
ct_flw_http_mthd    0
is_ftp_login        0
ct_ftp_cmd          1
ct_srv_src          1
ct_srv_dst          1
ct_dst_ltm       

In [ ]:
# Count the total number of NaN values in the entire DataFrame
total_nan_count = merged_df.isnull().sum().sum()

# Print the total number of NaN values
print("Total number of NaN values in the entire DataFrame:", total_nan_count)


Total number of NaN values in the entire DataFrame: 10


In [ ]:
# Number of columns with NaN values
columns_with_nan = merged_df.columns[merged_df.isnull().any()]
num_columns_with_nan = len(columns_with_nan)

# Number of rows with NaN values
rows_with_nan = merged_df[merged_df.isnull().any(axis=1)]
num_rows_with_nan = len(rows_with_nan)

# Print the results
print("Number of columns with NaN values:", num_columns_with_nan)
print("Number of rows with NaN values:", num_rows_with_nan)


Number of columns with NaN values: 10
Number of rows with NaN values: 1


In [ ]:
# Replace NaNs in 'attack_cat' column with 'normal'
merged_df['attack_cat'].fillna('normal', inplace=True)

# Replace NaNs in 'ct_flw_http_mthd' and 'is_ftp_login' columns with '0'
merged_df['ct_flw_http_mthd'].fillna(0, inplace=True)
merged_df['is_ftp_login'].fillna(0, inplace=True)

# Verifying the changes
print("Counts of NaN values after replacement:")
print(merged_df.isna().sum())


Counts of NaN values after replacement:
Unnamed: 0          0
srcip               0
sport               0
dstip               0
dsport              0
proto               0
state               0
dur                 0
sbytes              0
dbytes              0
sttl                0
dttl                0
sloss               0
dloss               0
service             0
Sload               0
Dload               0
Spkts               0
Dpkts               0
swin                0
dwin                0
stcpb               0
dtcpb               0
smeansz             0
dmeansz             0
trans_depth         0
res_bdy_len         0
Sjit                0
Djit                0
Stime               0
Ltime               0
Sintpkt             0
Dintpkt             0
tcprtt              0
synack              0
ackdat              0
is_sm_ips_ports     0
ct_state_ttl        0
ct_flw_http_mthd    0
is_ftp_login        0
ct_ftp_cmd          1
ct_srv_src          1
ct_srv_dst          1
ct_dst_ltm    

In [ ]:
# Number of columns with NaN values
columns_with_nan = merged_df.columns[merged_df.isnull().any()]
num_columns_with_nan = len(columns_with_nan)

# Number of rows with NaN values
rows_with_nan = merged_df[merged_df.isnull().any(axis=1)]
num_rows_with_nan = len(rows_with_nan)

# Print the results
print("Number of columns with NaN values:", num_columns_with_nan)
print("Number of rows with NaN values:", num_rows_with_nan)


Number of columns with NaN values: 36
Number of rows with NaN values: 1


In [ ]:
# Remove rows with NaN values
merged_df.dropna(inplace=True)

# Reset index after dropping rows
merged_df.reset_index(drop=True, inplace=True)


In [ ]:
# Number of columns with NaN values
columns_with_nan = merged_df.columns[merged_df.isnull().any()]
num_columns_with_nan = len(columns_with_nan)

# Number of rows with NaN values
rows_with_nan = merged_df[merged_df.isnull().any(axis=1)]
num_rows_with_nan = len(rows_with_nan)

# Print the results
print("Number of columns with NaN values:", num_columns_with_nan)
print("Number of rows with NaN values:", num_rows_with_nan)

Number of columns with NaN values: 0
Number of rows with NaN values: 0


In [ ]:
merged_df['state'].unique()

array(['CON', 'INT', 'FIN', 'URH', 'REQ', 'ECO', 'RST', 'CLO', 'TXD',
       'URN', 'no', 'ACC', 'PAR', 'MAS'], dtype=object)

In [ ]:
# Replace '-' entries in the 'state' column with 'othrs'
merged_df['state'].replace('-', 'othrs', inplace=True)


In [ ]:
merged_df['proto'].unique()

array(['udp', 'arp', 'tcp', 'ospf', 'icmp', 'igmp', 'sctp', 'udt', 'sep',
       'sun-nd', 'swipe', 'mobile', 'pim', 'rtp', 'ipnip', 'ip', 'ggp',
       'st2', 'egp', 'cbt', 'emcon', 'nvp', 'igp', 'xnet', 'argus',
       'bbn-rcc', 'chaos', 'pup', 'hmp', 'mux', 'dcn', 'prm', 'trunk-1',
       'xns-idp', 'trunk-2', 'leaf-1', 'leaf-2', 'irtp', 'rdp', 'iso-tp4',
       'netblt', 'mfe-nsp', 'merit-inp', '3pc', 'xtp', 'idpr', 'tp++',
       'ddp', 'idpr-cmtp', 'ipv6', 'il', 'idrp', 'ipv6-frag', 'sdrp',
       'ipv6-route', 'gre', 'rsvp', 'mhrp', 'bna', 'esp', 'i-nlsp',
       'narp', 'ipv6-no', 'tlsp', 'skip', 'ipv6-opts', 'any', 'cftp',
       'sat-expak', 'kryptolan', 'rvd', 'ippc', 'sat-mon', 'ipcv', 'visa',
       'cpnx', 'cphb', 'wsn', 'pvp', 'br-sat-mon', 'wb-mon', 'wb-expak',
       'iso-ip', 'secure-vmtp', 'vmtp', 'vines', 'ttp', 'nsfnet-igp',
       'dgp', 'tcf', 'eigrp', 'sprite-rpc', 'larp', 'mtp', 'ax.25',
       'ipip', 'micp', 'aes-sp3-d', 'encap', 'etherip', 'pri-enc', 'gmtp'

In [ ]:
merged_df['state'].unique()

array(['CON', 'INT', 'FIN', 'URH', 'REQ', 'ECO', 'RST', 'CLO', 'TXD',
       'URN', 'no', 'ACC', 'PAR', 'MAS'], dtype=object)

In [ ]:
merged_df['service'].unique()

array(['dns', 'othrs', 'http', 'smtp', 'ftp-data', 'ftp', 'ssh', 'pop3',
       'snmp', 'ssl', 'irc', 'radius', 'dhcp'], dtype=object)

In [ ]:
# Replace '-' entries in the 'state' column with 'othrs'
merged_df['service'].replace('-', 'othrs', inplace=True)

In [ ]:
merged_df.shape

(92342, 50)

In [ ]:
# data.head()

In [ ]:
# data.info()

In [ ]:
# Checking the Unique value counts of categorical columns: srcip, dstip, dsport, state, proto, and service

# List of columns
columns_to_check = ['srcip', 'dstip', 'dsport', 'state', 'proto', 'service', 'attack_cat']

# Print count of unique variables for each column
for column in columns_to_check:
    unique_count = merged_df[column].nunique()
    print(f"Unique count of variables in '{column}': {unique_count}")


Unique count of variables in 'srcip': 39
Unique count of variables in 'dstip': 42
Unique count of variables in 'dsport': 20913
Unique count of variables in 'state': 14
Unique count of variables in 'proto': 135
Unique count of variables in 'service': 13
Unique count of variables in 'attack_cat': 10


In [ ]:
# Get the list of categorical columns
categorical_columns = merged_df_copy.select_dtypes(include=['object', 'category']).columns.tolist()

# Print the list of categorical columns
print("Categorical columns:", categorical_columns)


Categorical columns: ['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'service', 'attack_cat']


In [ ]:
merged_df_copy['state'].unique()

array(['CON', 'INT', 'FIN', 'URH', 'REQ', 'ECO', 'RST', 'CLO', 'TXD',
       'URN', 'no', 'ACC', 'PAR', 'MAS', 'TST'], dtype=object)

In [ ]:
# print(data['service'].unique())

In [ ]:
# Count the occurrences of each unique value in the 'attack_cat' column
attack_cat_counts = merged_df['attack_cat'].value_counts(dropna=False)

# Print the counts of each unique value
print("Counts of each unique value in the 'attack_cat' column:")
print(attack_cat_counts)

Counts of each unique value in the 'attack_cat' column:
attack_cat
normal            82277
Exploits           3207
 Fuzzers           3102
Generic             972
Reconnaissance      875
DoS                 821
Backdoors           492
Analysis            464
Shellcode           117
Worms                15
Name: count, dtype: int64


In [ ]:
# Filter columns with values starting with '0xc0a8'
columns_with_values = merged_df.columns[merged_df.astype(str).apply(lambda x: x.str.contains('^0xc0a8')).any()]

# Print the columns
print("Columns with values starting with '0xc0a8':")
print(columns_with_values)


Columns with values starting with '0xc0a8':
Index(['dsport'], dtype='object')


In [ ]:
# Count occurrences of '0xc0a8' in the 'dsport' column
count_0xc0a8 = (merged_df['dsport'] == '0xc0a8').sum()

# Find the rows where '0xc0a8' appears in the 'dsport' column
rows_with_0xc0a8 = merged_df[merged_df['dsport'] == '0xc0a8']

# Count the number of rows where '0xc0a8' appears
num_rows_with_0xc0a8 = len(rows_with_0xc0a8)

# Print the count of occurrences and the number of rows
print("Count of '0xc0a8' in the 'dsport' column:", count_0xc0a8)
print("Number of rows where '0xc0a8' appears in the 'dsport' column:", num_rows_with_0xc0a8)


Count of '0xc0a8' in the 'dsport' column: 54
Number of rows where '0xc0a8' appears in the 'dsport' column: 54


In [ ]:
# Remove rows where '0xc0a8' appears in the 'dsport' column
merged_df = merged_df[merged_df['dsport'] != '0xc0a8']


In [ ]:
# Create a copy of the DataFrame
merged_df_copy = merged_df.copy()


In [ ]:
# Drop the column named "Unnamed: 0"
merged_df_copy.drop(columns=['Unnamed: 0'], inplace=True)


In [ ]:
merged_df_copy

srcip  sport          dstip dsport proto state       dur  \
0       59.166.0.0   1390  149.171.126.6     53   udp   CON  0.001055   
1       59.166.0.0  33661  149.171.126.9   1024   udp   CON  0.036133   
2       59.166.0.6   1464  149.171.126.7     53   udp   CON  0.001119   
3       59.166.0.5   3593  149.171.126.5     53   udp   CON  0.001209   
4       59.166.0.3  49664  149.171.126.0     53   udp   CON  0.001169   
...            ...    ...            ...    ...   ...   ...       ...   
139525  59.166.0.0  52708  149.171.126.2  50651   tcp   FIN  0.020871   
139526  59.166.0.8  40084  149.171.126.4     22   tcp   FIN  0.126838   
139527  59.166.0.9   7663  149.171.126.8     22   tcp   FIN  0.094723   
139528  59.166.0.3  33662  149.171.126.0  31721   tcp   FIN  0.020988   
139529  59.166.0.4  62577  149.171.126.8     80   tcp   FIN  1.008934   

         sbytes   dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  \
0         132.0    164.0  31.0  ...         0.0         3.0         7.0   
1         528.0    304.0  31.0  ...         0.0         2.0         4.0   
2         146.0    178.0  31.0  ...         0.0        12.0         8.0   
3         132.0    164.0  31.0  ...         0.0         6.0         9.0   
4         146.0    178.0  31.0  ...         0.0         7.0         9.0   
...         ...      ...   ...  ...         ...         ...         ...   
139525   3390.0  41676.0  31.0  ...         0.0         7.0        10.0   
139526   3728.0   5474.0  31.0  ...         0.0        10.0        11.0   
139527  14512.0  17134.0  31.0  ...         0.0        10.0         7.0   
139528   3390.0  41676.0  31.0  ...         0.0        10.0         9.0   
139529   1580.0  10168.0  31.0  ...         NaN         NaN         NaN   

       ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  \
0             1.0          3.0               1.0               1.0   
1             2.0          3.0               1.0               1.0   
2             1.0          2.0               2.0               1.0   
3             1.0          1.0               1.0               1.0   
4             1.0          1.0               1.0               1.0   
...           ...          ...               ...               ...   
139525        2.0          2.0               1.0               1.0   
139526        5.0          3.0               1.0               1.0   
139527        4.0          2.0               1.0               1.0   
139528        1.0          6.0               1.0               1.0   
139529        NaN          NaN               NaN               NaN   

        ct_dst_src_ltm  attack_cat  Label  
0                  1.0      normal    0.0  
1                  2.0      normal    0.0  
2                  1.0      normal    0.0  
3                  1.0      normal    0.0  
4                  1.0      normal    0.0  
...                ...         ...    ...  
139525             2.0      normal    0.0  
139526             3.0      normal    0.0  
139527             1.0      normal    0.0  
139528             1.0      normal    0.0  
139529             NaN      normal    NaN  

[139476 rows x 49 columns]

In [ ]:
X = merged_df_copy.iloc[:, 0:49].values
y = merged_df_copy.iloc[:, -1].values

In [ ]:
y[0:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
X[:, 4:5]

array([['udp'],
       ['udp'],
       ['udp'],
       ...,
       ['tcp'],
       ['tcp'],
       ['tcp']], dtype=object)

In [ ]:
X[:, 5:6]

array([['CON'],
       ['CON'],
       ['CON'],
       ...,
       ['FIN'],
       ['FIN'],
       ['FIN']], dtype=object)

In [ ]:
X[:, 47:48]

array([['normal'],
       ['normal'],
       ['normal'],
       ...,
       ['normal'],
       ['normal'],
       ['normal']], dtype=object)

In [ ]:
merged_df_copy.to_csv('merged_cleaned1.csv')

In [ ]:
merged_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 139476 entries, 0 to 139529
Data columns (total 49 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   srcip             139476 non-null  object 
 1   sport             139476 non-null  object 
 2   dstip             139476 non-null  object 
 3   dsport            139476 non-null  object 
 4   proto             139476 non-null  object 
 5   state             139476 non-null  object 
 6   dur               139476 non-null  float64
 7   sbytes            139476 non-null  float64
 8   dbytes            139476 non-null  float64
 9   sttl              139476 non-null  float64
 10  dttl              139476 non-null  float64
 11  sloss             139476 non-null  float64
 12  dloss             139476 non-null  float64
 13  service           139476 non-null  object 
 14  Sload             139476 non-null  float64
 15  Dload             139476 non-null  float64
 16  Spkts             139476 

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

# # Convert all values in the columns to strings
# X[:, 4:6] = X[:, 4:6].astype(str)

# # Initialize the OrdinalEncoder
# encoder = OrdinalEncoder()

# # Encode the "proto" column
# X[:, 4:5] = encoder.fit_transform(X[:, 4:5])

# # Encode the "state" column
# X[:, 5:6] = encoder.fit_transform(X[:, 5:6])


In [ ]:
merged_df_copy

srcip  sport          dstip dsport proto state       dur  \
0       59.166.0.0   1390  149.171.126.6     53   udp   CON  0.001055   
1       59.166.0.0  33661  149.171.126.9   1024   udp   CON  0.036133   
2       59.166.0.6   1464  149.171.126.7     53   udp   CON  0.001119   
3       59.166.0.5   3593  149.171.126.5     53   udp   CON  0.001209   
4       59.166.0.3  49664  149.171.126.0     53   udp   CON  0.001169   
...            ...    ...            ...    ...   ...   ...       ...   
139525  59.166.0.0  52708  149.171.126.2  50651   tcp   FIN  0.020871   
139526  59.166.0.8  40084  149.171.126.4     22   tcp   FIN  0.126838   
139527  59.166.0.9   7663  149.171.126.8     22   tcp   FIN  0.094723   
139528  59.166.0.3  33662  149.171.126.0  31721   tcp   FIN  0.020988   
139529  59.166.0.4  62577  149.171.126.8     80   tcp   FIN  1.008934   

         sbytes   dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  \
0         132.0    164.0  31.0  ...         0.0         3.0         7.0   
1         528.0    304.0  31.0  ...         0.0         2.0         4.0   
2         146.0    178.0  31.0  ...         0.0        12.0         8.0   
3         132.0    164.0  31.0  ...         0.0         6.0         9.0   
4         146.0    178.0  31.0  ...         0.0         7.0         9.0   
...         ...      ...   ...  ...         ...         ...         ...   
139525   3390.0  41676.0  31.0  ...         0.0         7.0        10.0   
139526   3728.0   5474.0  31.0  ...         0.0        10.0        11.0   
139527  14512.0  17134.0  31.0  ...         0.0        10.0         7.0   
139528   3390.0  41676.0  31.0  ...         0.0        10.0         9.0   
139529   1580.0  10168.0  31.0  ...         NaN         NaN         NaN   

       ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  \
0             1.0          3.0               1.0               1.0   
1             2.0          3.0               1.0               1.0   
2             1.0          2.0               2.0               1.0   
3             1.0          1.0               1.0               1.0   
4             1.0          1.0               1.0               1.0   
...           ...          ...               ...               ...   
139525        2.0          2.0               1.0               1.0   
139526        5.0          3.0               1.0               1.0   
139527        4.0          2.0               1.0               1.0   
139528        1.0          6.0               1.0               1.0   
139529        NaN          NaN               NaN               NaN   

        ct_dst_src_ltm  attack_cat  Label  
0                  1.0      normal    0.0  
1                  2.0      normal    0.0  
2                  1.0      normal    0.0  
3                  1.0      normal    0.0  
4                  1.0      normal    0.0  
...                ...         ...    ...  
139525             2.0      normal    0.0  
139526             3.0      normal    0.0  
139527             1.0      normal    0.0  
139528             1.0      normal    0.0  
139529             NaN      normal    NaN  

[139476 rows x 49 columns]

In [ ]:
# Get the list of categorical columns
categorical_columns = merged_df_copy.select_dtypes(include=['object', 'category']).columns.tolist()

# Print the list of categorical columns
print("Categorical columns:", categorical_columns)


Categorical columns: ['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'service', 'attack_cat']


In [ ]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

# Encode the "proto" column
merged_df_copy.loc[:, 'proto'] = np.array(encoder.fit_transform(merged_df_copy.loc[:, 'proto'].to_numpy().reshape(-1, 1))) # For Proto
merged_df_copy.loc[:, 'state'] = np.array(encoder.fit_transform(merged_df_copy.loc[:, 'state'].to_numpy().reshape(-1, 1))) # For State
merged_df_copy.loc[:, 'attack_cat'] = np.array(encoder.fit_transform(merged_df_copy.loc[:, 'attack_cat'].to_numpy().reshape(-1, 1))) # For Attack_Cat
merged_df_copy.loc[:, 'service'] = np.array(encoder.fit_transform(merged_df_copy.loc[:, 'service'].to_numpy().reshape(-1, 1))) # For service

In [ ]:
len(merged_df_copy)

139476

In [ ]:
X[:, 4:5]

array([[120.0],
       [120.0],
       [120.0],
       ...,
       [114.0],
       [114.0],
       [114.0]], dtype=object)

In [ ]:
X[:, 5:6]

array([[2.0],
       [2.0],
       [2.0],
       ...,
       [4.0],
       [4.0],
       [4.0]], dtype=object)

In [ ]:
X[:, 14:15]

array([[54040.0],
       [34189.0],
       [54726.0],
       ...,
       [74073.0],
       [74844.0],
       [14112.0]], dtype=object)

In [ ]:
X[:, 47]

array([9.0, 9.0, 9.0, ..., 9.0, 9.0, 9.0], dtype=object)

In [ ]:
# Find the index of the 'attack_cat' column
attack_cat_index = merged_df.columns.get_loc('service')
print(attack_cat_index)

14


In [ ]:
# Encode the "attack_cat" column
X[:, 47:48] = np.array(encoder.fit_transform(X[:, 47:48]))


In [ ]:
X[:, 47]

array([9.0, 9.0, 9.0, ..., 9.0, 9.0, 9.0], dtype=object)

In [ ]:
# # Count the number of NaN values in the 'attack_cat' column
# nan_count = np.sum(pd.isnull(X[:, 47]))

# # Print the count of NaN values
# print("Number of NaN values in the 'attack_cat' column:", nan_count)


In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

# # List of columns to encode
# columns_to_encode = ['srcip', 'sport', 'dstip', 'proto', 'state', 'service', 'attack_cat']

# # Convert the columns to strings
# data[columns_to_encode] = data[columns_to_encode].astype(str)

# # Initialize the OrdinalEncoder
# encoder = OrdinalEncoder()

# # Fit-transform the encoder on the specified columns in 'data' DataFrame
# data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

# # Display the encoded DataFrame
# print(data)


In [ ]:
# # Checking the Unique value counts of categorical columns: srcip, dstip, dsport, state, proto, and service

# # List of columns
# columns_to_check = ['srcip', 'dstip', 'dsport', 'state', 'proto', 'service']

# # Print count of unique variables for each column
# for column in columns_to_check:
#     unique_count = data[column].nunique()
#     print(f"Unique count of variables in '{column}': {unique_count}")

In [ ]:
# print(data['state'].unique())

In [ ]:
# print(data['proto'].unique())

In [ ]:
# print(data['attack_cat'].unique())

In [ ]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# # Define the ColumnTransformer
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1])], remainder='passthrough')

# # Apply the transformation to X
# # X = np.array(ct.fit_transform(X))
# merged_df_copy.loc[:, ('srcip', 'dstip')] = np.array(ct.fit_transform(merged_df_copy.loc[:, ('srcip', 'dstip')]))

In [ ]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# # Define the ColumnTransformer
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['srcip', 'dstip'])], remainder='passthrough')

# # Apply the transformation to the specified columns
# merged_df_copy_encoded = pd.DataFrame(ct.fit_transform(merged_df_copy), columns=ct.get_feature_names_out(['srcip', 'dstip']) + list(merged_df_copy.columns[2:]))

# # Display the encoded DataFrame
# print(merged_df_copy_encoded)


In [ ]:
# from sklearn.preprocessing import OneHotEncoder

# # Initialize OneHotEncoder
# encoder = OneHotEncoder()

# # Encode the specified columns
# encoded_columns = encoder.fit_transform(merged_df_copy[['srcip', 'dstip']])

In [ ]:
# encoded_columns[0]

<1x81 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
# # Replace the original columns with the encoded values
# merged_df_copy[['srcip', 'dstip']] = encoded_columns.toarray()

# # Display the updated DataFrame
# print(merged_df_copy)

In [ ]:
# from sklearn.preprocessing import OneHotEncoder

# # Initialize OneHotEncoder
# encoder = OneHotEncoder()

# # Encode the specified columns
# encoded_columns = encoder.fit_transform(merged_df_copy[['srcip', 'dstip']])

# # Convert the encoded values to a DataFrame
# encoded_df = pd.DataFrame(encoded_columns.toarray(), columns=encoder.get_feature_names_out(['srcip', 'dstip']))

# # Replace the original columns with the encoded values
# merged_df_copy.drop(columns=['srcip', 'dstip'], inplace=True)
# merged_df_copy = pd.concat([merged_df_copy, encoded_df], axis=1)

# # Display the updated DataFrame
# print(merged_df_copy)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Initialize OneHotEncoder
encoder = OneHotEncoder()

# Encode the specified columns
encoded_columns = encoder.fit_transform(merged_df_copy[['srcip', 'dstip']])

# Get the encoded column names
encoded_column_names = encoder.get_feature_names_out(['srcip', 'dstip'])

# Convert the encoded values to a DataFrame
encoded_df = pd.DataFrame(encoded_columns.toarray(), columns=encoded_column_names)

# Replace the original 'srcip' column with the corresponding encoded values
merged_df_copy['srcip'] = encoded_df.iloc[:, :len(encoder.categories_[0])]

# Replace the original 'dstip' column with the corresponding encoded values
merged_df_copy['dstip'] = encoded_df.iloc[:, len(encoder.categories_[0]):]

# Display the updated DataFrame
print(merged_df_copy)


ValueError: Columns must be same length as key

In [ ]:
len(merged_df_copy.columns)

128

In [ ]:
merged_df_copy

srcip  sport  \
0         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...   1390   
1         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  33661   
2         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...   1464   
3         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...   3593   
4         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  49664   
...                                                   ...    ...   
139525    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  52708   
139526    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  40084   
139527    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...   7663   
139528    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  33662   
139529    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  62577   

                                                    dstip dsport proto state  \
0         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     53   udp   CON   
1         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...   1024   udp   CON   
2         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     53   udp   CON   
3         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     53   udp   CON   
4         (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     53   udp   CON   
...                                                   ...    ...   ...   ...   
139525    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  50651   tcp   FIN   
139526    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     22   tcp   FIN   
139527    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     22   tcp   FIN   
139528    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...  31721   tcp   FIN   
139529    (0, 29)\t1.0\n  (0, 59)\t1.0\n  (1, 29)\t1.0...     80   tcp   FIN   

             dur   sbytes   dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  \
0       0.001055    132.0    164.0  31.0  ...         0.0         3.0   
1       0.036133    528.0    304.0  31.0  ...         0.0         2.0   
2       0.001119    146.0    178.0  31.0  ...         0.0        12.0   
3       0.001209    132.0    164.0  31.0  ...         0.0         6.0   
4       0.001169    146.0    178.0  31.0  ...         0.0         7.0   
...          ...      ...      ...   ...  ...         ...         ...   
139525  0.020871   3390.0  41676.0  31.0  ...         0.0         7.0   
139526  0.126838   3728.0   5474.0  31.0  ...         0.0        10.0   
139527  0.094723  14512.0  17134.0  31.0  ...         0.0        10.0   
139528  0.020988   3390.0  41676.0  31.0  ...         0.0        10.0   
139529  1.008934   1580.0  10168.0  31.0  ...         NaN         NaN   

        ct_srv_dst ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  \
0              7.0        1.0          3.0               1.0   
1              4.0        2.0          3.0               1.0   
2              8.0        1.0          2.0               2.0   
3              9.0        1.0          1.0               1.0   
4              9.0        1.0          1.0               1.0   
...            ...        ...          ...               ...   
139525        10.0        2.0          2.0               1.0   
139526        11.0        5.0          3.0               1.0   
139527         7.0        4.0          2.0               1.0   
139528         9.0        1.0          6.0               1.0   
139529         NaN        NaN          NaN               NaN   

        ct_dst_sport_ltm  ct_dst_src_ltm  attack_cat  Label  
0                    1.0             1.0      normal    0.0  
1                    1.0             2.0      normal    0.0  
2                    1.0             1.0      normal    0.0  
3                    1.0             1.0      normal    0.0  
4                    1.0             1.0      normal    0.0  
...                  ...             ...         ...    ...  
139525               1.0             2.0      normal    0.0  
139526               1.0             3.0      normal    0.0  
139527               1.0             1.0      normal    0.0  
139528  

In [ ]:
merged_df_copy.columns

Index(['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'dur', 'sbytes',
       'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload',
       'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz',
       'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Stime',
       'Ltime', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat',
       'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login',
       'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat',
       'Label'],
      dtype='object')

In [ ]:
type(merged_df_copy.loc[:, ['srcip', 'dstip']])

pandas.core.frame.DataFrame

In [ ]:
X[:, 0]

array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=1)

In [ ]:
X

array([[0.0, 0.0, 0.0, ..., 1.0, 9.0, 0.0],
       [0.0, 0.0, 0.0, ..., 2.0, 9.0, 0.0],
       [0.0, 0.0, 0.0, ..., 1.0, 9.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 1.0, 9.0, 0.0],
       [0.0, 0.0, 0.0, ..., 1.0, 9.0, 0.0],
       [0.0, 0.0, 0.0, ..., nan, 9.0, nan]], dtype=object)

In [ ]:
y

array([ 0.,  0.,  0., ...,  0.,  0., nan])

In [ ]:
X.shape

(139476, 128)

In [ ]:
y.shape

(139476,)

In [ ]:
X_frame = np.concatenate((X, y), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Assuming X is a 2D array and y is a 1D array
# Reshape y to a column vector to match the number of rows in X
y_column_vector = y.reshape(-1, 1)

# Concatenate X and y_column_vector along axis 1 (columns)
X_frame = np.concatenate((X, y_column_vector), axis=1)


In [ ]:
len(X.shape)

2

In [ ]:
import pandas as pd

# Assuming X_frame is a NumPy array and column_names is a list of column names
df = pd.DataFrame(X_frame, columns=[
    'srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'dur', 'sbytes', 'dbytes',
    'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload', 'Spkts', 'Dpkts',
    'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len',
    'Sjit', 'Djit', 'Stime', 'Ltime', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat',
    'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_ftp_cmd',
    'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ ltm', 'ct_src_dport_ltm',
    'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat', 'Label'
])


ValueError: Shape of passed values is (139476, 129), indices imply (139476, 49)

In [ ]:
import pandas as pd

# Assuming X_frame is a NumPy array
df = pd.DataFrame(X_frame)

# You might also want to set column names for the DataFrame
# Assuming column_names is a list of column names for X_frame
df.columns = column_names


NameError: name 'column_names' is not defined

In [ ]:
X_frame.columns

RangeIndex(start=0, stop=128, step=1)

In [ ]:
merged_x_y = pd.DataFrame({
    'X': X,
    'y': y,}, columns=[X.columns])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
merged_x_y

array([0.0, 0.0, 0.0, ..., 0.0, 0.0, nan], dtype=object)

In [ ]:
# Assuming 'data' is your DataFrame containing the 'attack_cat' column

# Get the summary count of each unique value in the 'attack_cat' column
attack_cat_counts = data['attack_cat'].value_counts()

# Print the summary count
print("Summary count of each unique value in the 'attack_cat' column:")
print(attack_cat_counts)


In [ ]:
len(data.columns)

In [ ]:
# Iterate through each column in the DataFrame
for column in data.columns:
    # Check if the data type of the column is 'object'
    if data[column].dtype == 'object':
        print(f"Column '{column}' contains uncoded categorical data.")


In [ ]:
# Assuming 'data' is your DataFrame containing the 'dsport column

# Get the summary count of each unique value in the 'dsport' column
desport_counts = data['dsport'].value_counts()

# Print the summary count
print("Summary count of each unique value in the 'dsport' column:")
print(desport_counts)

In [ ]:
# Check the data type of the 'dsport' column
print("Data type of 'dsport' column:", data['dsport'].dtype)


In [ ]:
# Check the data types of all columns in the DataFrame
print("Data types of all columns:")
print(data.info())


In [ ]:
# Convert 'dsport' column to numeric data type
data['dsport'] = pd.to_numeric(data['dsport'], errors='coerce')

# Check the data type of the 'dsport' column after conversion
print("Data type of 'dsport' column after conversion:", data['dsport'].dtype)


In [ ]:
# Iterate through each column in the DataFrame
for column in data.columns:
    # Check if the data type of the column is 'object'
    if data[column].dtype == 'object':
        print(f"Column '{column}' contains uncoded categorical data.")


In [ ]:
# double checking for columns or possibilities of the presence of NaN or blank/empty cells

# Iterate through each column in the DataFrame
for column in data.columns:
    # Check for NaN values in the column
    if data[column].isnull().any():
        print(f"Column '{column}' contains NaN values.")

    # Check for empty cells (blanks) in the column
    if (data[column] == '').any():
        print(f"Column '{column}' contains empty cells.")


In [ ]:
# Find the indices of NaN values in the 'dsport' column
nan_indices = data[data['dsport'].isnull()].index

# Count the occurrences of NaN values in the 'dsport' column
nan_count = data['dsport'].isnull().sum()

# Print the location and count of NaN values
print("Indices of NaN values in the 'dsport' column:", nan_indices)



In [ ]:
print("Number of NaN values in the 'dsport' column:", nan_count)

In [ ]:
# Drop rows where 'dsport' column contains NaN values
data.dropna(subset=['dsport'], inplace=True)


In [ ]:
# Find the indices of NaN values in the 'dsport' column
nan_indices = data[data['dsport'].isnull()].index

# Count the occurrences of NaN values in the 'dsport' column
nan_count = data['dsport'].isnull().sum()

# Print the location and count of NaN values
print("Indices of NaN values in the 'dsport' column:", nan_indices)



In [ ]:
print("Number of NaN values in the 'dsport' column:", nan_count)

In [ ]:
print(data.head)

In [ ]:
# Check for NaN values in the entire DataFrame
nan_rows = data.isnull().any(axis=1)

# Count the number of rows with NaN values
nan_count_total = nan_rows.sum()

# Print the count of rows with NaN values
print("Number of rows with NaN values:", nan_count_total)


In [ ]:
len((data.columns))

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
np.random.seed(0)  # for reproducibility
data = {
    'ab': np.random.rand(100),
    'ac': np.random.choice(['A', 'B', 'C'], size=100),
    'ad': np.random.rand(100),
    'ae': np.random.rand(100),
    'af': np.random.rand(100),
    'au': np.random.choice(['X', 'Y', 'Z'], size=100)
}
df = pd.DataFrame(data)

# Display the sample DataFrame
print(df.head())


         ab ac        ad        ae        af au
0  0.548814  B  0.489549  0.787542  0.580197  Z
1  0.715189  C  0.338985  0.606475  0.716244  Y
2  0.602763  C  0.179490  0.218403  0.027069  Z
3  0.544883  C  0.170987  0.455169  0.731397  Y
4  0.423655  B  0.463451  0.878870  0.766964  Z


In [ ]:
df['ac'].unique()

array(['B', 'C', 'A'], dtype=object)